[project]
name = "galatea"
version = "0.0.2.dev0"
requires-python = ">= 3.10"

[project.scripts]
galatea = "galatea.cli:main"

[build-system]
requires = ["setuptools>=75.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["galatea"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
