[project]
name = "galatea"
version = "0.0.1"

[project.scripts]
galatea = "galatea.cli:main"

[build-system]
requires = ["setuptools>=75.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["galatea"]