[tox]
envlist = py3{10-14},py314t

[testenv:py3{10-}]
package=wheel
dependency_groups = test
extras=gui
commands = pytest --basetemp={envtmpdir} -v

[testenv:py3{14-}t]
package=wheel
dependency_groups = test
commands = pytest --basetemp={envtmpdir} -v